dist: replace license classifier with SPDX expressions
Present in pyproject.toml and setup.cfg.

Avoids:

  ********************************************************************************
  Please consider removing the following classifiers in favor of a SPDX license expression:

  License :: OSI Approved :: GNU General Public License v2 (GPLv2)

  See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
  ********************************************************************************

Note that the mentioned URL refers to status as of PEP639: this was
accepted in August 2024. As of 2025 setuptools and flit do not support
PEP639 and distributions may be lagging on shipping other components.

In particular the suggested "license = "$SPDX-expression" does not work
with current Fedora packaging, failing with an error that suggests there
are multiple definitions of the value:

  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  configuration error: `project.license` must be valid exactly by one definition (2 matches found):

      - keys:
          'file': {type: string}
        required: ['file']
      - keys:
          'text': {type: string}
        required: ['text']

  DESCRIPTION:
      `Project license <https://peps.python.org/pep-0621/#license>`_.

  GIVEN VALUE:
      "GPL-2.0-only AND Apache-2.0"

  OFFENDING RULE: 'oneOf'

  DEFINITION:
      {
          "oneOf": [
              {
                  "properties": {
                      "file": {
                          "type": "string",
                          "$$description": [
                              "Relative path to the file (UTF-8) which contains the license for the",
                              "project."
                          ]
                      }
                  },
                  "required": [
                      "file"
                  ]
              },
              {
                  "properties": {
                      "text": {
                          "type": "string",
                          "$$description": [
                              "The license of the project whose meaning is that of the",
                              "`License field from the core metadata",
                              "<https://packaging.python.org/specifications/core-metadata/#license>`_."
                          ]
                      }
                  },
                  "required": [
                      "text"
                  ]
              }
          ]
      }

This also seems to imply that the structure of the value should be a
block with either file= or text= assignments. Setting the value to:

license= { text="$SPDX-expression" }

This corresponds to the 'Legacy license declaration' in the link:

  https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license

So this will presumably break again once the new definitions of the
field begin to flow through to distros (when the field becomes a plain
string).

Passes local builds with both setuptools and wheel.

Resolves: #142